AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS CloudFormation Template Final - Fullstack Vue + Node.js + PostgreSQL.
  - Setup Frontend (Vue/Apache) di Public Subnet.
  - Setup Backend (Node/PM2) di Private Subnet (Port 5000).
  - Setup Database (PostgreSQL) di Private Subnet (Port 5432).
  - Load Balancer Routing (/api ke Backend, sisa ke Frontend).
  - Auto Swap 2GB di semua instance.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block untuk VPC utama

  InstanceType:
    Type: String
    Default: t3.micro
    Description: Tipe instance EC2 (default t3.micro)

  LatestUbuntuAmi:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id
    Description: AMI Ubuntu 24.04 terbaru

Resources:
  # ================= NETWORK =================
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MainVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MainVPC-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref MyVPC

  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: NAT-EIP

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: My-NAT-Gateway

  # ================= SUBNETS =================
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-southeast-1a
      Tags:
        - Key: Name
          Value: Public-Subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-southeast-1b
      Tags:
        - Key: Name
          Value: Public-Subnet-2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-southeast-1a
      Tags:
        - Key: Name
          Value: Private-Subnet-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: ap-southeast-1b
      Tags:
        - Key: Name
          Value: Private-Subnet-2

  # ================= ROUTES =================
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Public-RT

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Private-RT

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  # ================= SECURITY GROUPS =================
  SecurityGroupFrontend:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP for Frontend
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-Frontend

  SecurityGroupALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS access to ALB
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-ALB

  SecurityGroupBackend:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB to Backend Port 5000
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        # UPDATE: Allow Port 5000 dari ALB
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          SourceSecurityGroupId: !Ref SecurityGroupALB
      Tags:
        - Key: Name
          Value: SG-Backend

  SecurityGroupDB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL access from backend only
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        # UPDATE: Ganti ke Port Postgres (5432)
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref SecurityGroupBackend
      Tags:
        - Key: Name
          Value: SG-DB

  # ================= IAM ROLE =================
  SSMAndS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${S3Bucket.Arn}"
                  - !Sub "${S3Bucket.Arn}/*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref SSMAndS3Role

  # ================= INSTANCES =================
  FrontendInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestUbuntuAmi
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref SecurityGroupFrontend
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: Frontend-1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # 1. Swap Setup (2GB)
          fallocate -l 2G /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab

          # 2. Apache Setup
          apt update -y
          apt install -y apache2 zip unzip
          systemctl enable apache2
          systemctl start apache2
          echo "<h1>Frontend-1 Ready (Deploy Vue Here)</h1>" > /var/www/html/index.html

  FrontendInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestUbuntuAmi
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref SecurityGroupFrontend
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: Frontend-2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # 1. Swap Setup (2GB)
          fallocate -l 2G /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab

          # 2. Apache Setup
          apt update -y
          apt install -y apache2 zip unzip
          systemctl enable apache2
          systemctl start apache2
          echo "<h1>Frontend-2 Ready</h1>" > /var/www/html/index.html

  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestUbuntuAmi
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet1
      SecurityGroupIds:
        - !Ref SecurityGroupBackend
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: Backend
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # 1. Swap Setup (2GB) - Wajib buat npm install
          fallocate -l 2G /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab

          # 2. Install Node.js & Tools
          apt update -y
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt install -y nodejs
          npm install -g pm2
          # Backend siap digunakan (Manual Git Clone)

  DatabaseInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestUbuntuAmi
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet2
      SecurityGroupIds:
        - !Ref SecurityGroupDB
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: Database
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # 1. Swap Setup (2GB)
          fallocate -l 2G /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab

          # 2. Install PostgreSQL (UPDATE dari MySQL)
          apt update -y
          apt install -y postgresql postgresql-contrib

          # 3. Config Listen Address (Allow Remote)
          # Cari file config (asumsi versi 14/16, pake wildcard buat cari path)
          CONF_FILE=$(find /etc/postgresql -name postgresql.conf)
          HBA_FILE=$(find /etc/postgresql -name pg_hba.conf)

          # Ubah listen_addresses = '*'
          sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" $CONF_FILE

          # Ubah pg_hba.conf (Allow MD5 dari mana saja - aman krn dilindungi Security Group)
          echo "host    all             all             0.0.0.0/0               md5" >> $HBA_FILE

          # 4. Restart Postgres
          systemctl restart postgresql

          # Note: User database & DB nya dibuat manual via SSM psql

  # ================= LOAD BALANCER & ROUTING =================
  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: frontend-target-group
      Protocol: HTTP
      Port: 80
      VpcId: !Ref MyVPC
      TargetType: instance
      HealthCheckPath: /
      Targets:
        - Id: !Ref FrontendInstance1
          Port: 80
        # FrontendInstance2 sementara dikomen di target group biar traffic ke 1 dulu
        # - Id: !Ref FrontendInstance2
        #   Port: 80

  # UPDATE: Target Group buat Backend Port 5000
  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: backend-target-group
      Protocol: HTTP
      Port: 5000
      VpcId: !Ref MyVPC
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200-499
      Targets:
        - Id: !Ref BackendInstance
          Port: 5000

  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: frontend-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref SecurityGroupALB
      Tags:
        - Key: Name
          Value: Frontend-ALB

  ALBListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  # UPDATE: Rule buat belokin /api/* ke Backend
  ALBRuleApi:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListenerHTTP
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values: [/api/*]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  # ================= S3 BUCKET =================
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-assets-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcId: !Ref MyVPC
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable
        - !Ref PublicRouteTable
